paginate: 10

markdown: maruku
permalink: pretty

safe: true
lsi: false
pygments: true
baseurl: /plan-it

githubuser: atlregional

# prose.io settings
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  rooturl: 'data'
  siteurl: 'http://atlregional.github.io/plan-it/'
  # media: 'assets'
  # metadata:
  #   source/_posts:
  #     - name: "layout"
  #       field:
  #         element: "hidden"
  #         value: "post"
  #     - name: "title"
  #       field:
  #         element: "text"
  #         label: "Title"
  #         value: ""
  #         type: "text"
  #     - name: "author"
  #       field:
  #         element: "text"
  #         label: "Author"
  #         value: ""
  #         placeholder: "Trunk Botterson"
  #         type: "text"
  #     - name: "categories"
  #       field:
  #         element: "multiselect"
  #         label: "Post Category"
  #         placeholder: "Create or choose"
  #         alterable: true
  #     - name: "comments"
  #       field:
  #         element: checkbox
  #         label: "Comments"
  #         value: "true"
  #     - name: "tags"
  #       field:
  #         element: "multiselect"
  #         label: "Add Tags"
  #         placeholder: "Choose Tags"
  #         alterable: true